# Generated by Django 2.2.18 on 2021-03-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalregistrationformdb',
            fields=[
                ('hospital_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=30)),
                ('hospital_type', models.CharField(choices=[('general', 'General'), ('special', 'Special'), ('rehabilitationandchronicdisease', 'Rehabilitation and Chronic Disease'), ('psychiatric', 'Psychiatric ')], default='level1', max_length=15)),
                ('hospital_level', models.CharField(choices=[('level1', 'LEVEL 1'), ('level2', 'LEVEL 2'), ('level3', 'LEVEL 3'), ('level4', 'LEVEL 4'), ('level5', 'LEVEL 5'), ('level6', 'LEVEL 6')], default='higherlevel', max_length=8)),
                ('hospital_registration_response_one', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('hospital_registration_response_two', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('hospital_registration_response_three', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('hospital_registration_response_four', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('hospital_registration_response_five', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('hospital_registration_response_six', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('hospital_registration_response_seven', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('hospital_registration_response_eight', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('hospital_registration_response_nine', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('hospital_registration_response_ten', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='hospitalstaffregistrationformdb',
            fields=[
                ('hospital_clinic_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('national_passport_id', models.CharField(max_length=50)),
                ('staff_work_id', models.CharField(max_length=50)),
                ('hospital_clinic_name', models.CharField(max_length=30)),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='patientregistrationformdb',
            fields=[
                ('hospital_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=30)),
                ('id_birth_number', models.CharField(max_length=30)),
                ('nhif_number', models.CharField(max_length=30)),
                ('patient_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='schoolsregistrationformdb',
            fields=[
                ('school_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=30)),
                ('school_type', models.CharField(choices=[('university', 'University'), ('highschool', 'High School'), ('primary', 'Primary'), ('kindergarten', 'Kindergarten ')], default='university', max_length=15)),
                ('school_level', models.CharField(choices=[('higherinstitution', 'Higher Institution'), ('middleinstitution', 'Middle Institution'), ('lowerinstitution', 'Lower Institution')], default='higherinstitution', max_length=8)),
                ('school_registration_response_one', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('school_registration_response_two', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('school_registration_response_three', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('school_registration_response_four', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('school_registration_response_five', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('school_registration_response_six', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('school_registration_response_seven', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('school_registration_response_eight', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('school_registration_response_nine', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
                ('school_registration_response_ten', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='schoolstaffregistrationformdb',
            fields=[
                ('school_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=30)),
                ('national_passport_id', models.CharField(max_length=50)),
                ('staff_work_id', models.CharField(max_length=50)),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='studentregistrationformdb',
            fields=[
                ('school_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=30)),
                ('student_name', models.CharField(max_length=30)),
                ('student_pupil_id_birth_number', models.CharField(max_length=30)),
                ('student_pupil_number', models.CharField(max_length=30)),
                ('grade_year_number', models.CharField(max_length=30)),
            ],
        ),
    ]
